name: Deploy Memory Forensics Dashboard

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -c "import flask; print('Flask installed successfully')"
        python -c "import yara; print('YARA installed successfully')"
        python -c "import pandas; print('Pandas installed successfully')"
    
    - name: Check file structure
      run: |
        echo "Checking project structure..."
        ls -la
        echo "Checking scripts directory..."
        ls -la scripts/
        echo "Checking templates directory..."
        ls -la templates/
        echo "Checking static directory..."
        ls -la static/

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages 